Bella/activities
cuappdev/uplift-backend pull request #100
Opened 2023-04-15 20:46 UTC by isabellahoie

## Created Activity Model

## Overview

Created the activity model and a many to many relationship between the gyms and activities

## Changes Made

Created a new table for activities as well as a join table to create a many to many relationship with gyms; added the activities field to the Gym class in the schema and a corresponding resolver in order to be able to pass the name parameter into queries for activities of a certain gym; added the gyms field to the Activity class in the schema and a corresponding resolver in order to be able to pass the name parameter into queries for gyms of a certain activity; added root query for activities and a resolver enabling users to get activities by name

## Test Coverage

I tested this using manual testing- by creating objects in init_db() in the database.py file to populate the tables, and test that the resolvers function properly and return the correct information based on how they were defined in init_db().

## Next Steps 

The next steps are to begin working on the facilities model and its corresponding schema since it also has a relationship with gyms.

## Screenshots 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/68919125/232252394-1ac4a906-c414-4f08-a7b4-396e382bc61e.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/68919125/232252508-6c753248-584c-47d1-8406-4434083153ed.png">

2023-04-16 20:07 UTC, snajima requested changes
looks good! just a few style changes here and there, and also make sure ur PR name is formatted as [action verb] [feature]! e.g.: Implement activities model

2023-04-16 20:07 UTC, snajima commented on src/app2/models/activity.py
> +    details = Column(String(1000), nullable=False)
how were these character limits decided?

2023-04-16 20:07 UTC, snajima commented on src/app2/models/activity.py
> +    #amenities - rip
no commented code >:c

2023-04-16 20:07 UTC, snajima commented on src/app2/models/gym.py
>      #capacity = relation
ik u didn't make these changes but can we delete these commented lines too

2023-04-16 20:07 UTC, snajima commented on src/app2/schema.py
> +    #capacity = graphene.List(lambda: Capacity)
same problem here

2023-04-16 20:07 UTC, snajima commented on src/app2/schema.py
> +                    activity_queries.append(activity[0])
this can be condensed to 
```
if activity.first() and (name == act.name or not name):
   activity_queries.append(activity[0])
```

also, is the `not name` part checking if `name` is None or if it's an empty string? because `not name` will evaluate to True for either case. if you want only one of the cases, revise the condition

2023-04-16 20:07 UTC, snajima commented on src/app2/schema.py
> +                    gym_queries.append(gym[0])
same thing here - condense into one if statement

2023-04-16 20:07 UTC, snajima commented on src/app2/schema.py
> +    # node = relay.Node.Field()
no comment

2023-04-16 20:07 UTC, snajima commented on src/app2/schema.py
> +    ), details=graphene.String(), image_url=graphene.String())
if you're splitting into multiple lines, you need a `\` on the end of the first line and the second line should be indented

2023-04-16 23:15 UTC, markim21 reviewed
lgtm, I agree with shungo's change requests!

2023-04-19 21:13 UTC, isabellahoie commented on src/app2/models/activity.py
> +    #amenities - rip
my bad boss

2023-04-20 21:32 UTC, snajima approved these changes
lgtm! just make the minor stylistic fixes, and please rename ur PR! then we can merge this :)

2023-04-20 21:32 UTC, snajima commented on src/app2/models/activity.py
> +    name = Column(String(100), nullable=False)
let's get rid of all the character limits. the only times we need character limits are if:
1. for something like usernames/netids where some upper bound **has** to be enforced, or 
2. we want to prevent the user from entering too many characters into some open-form text field, like their instagram bio for example

2023-04-20 21:32 UTC, snajima commented on src/app2/schema.py
> +      if one_time != None:
`one_time is not None`

2023-04-21 04:58 UTC, markim21 requested changes
lgtm! only change that should be addressed before merging, remove `Base.metadata.drop_all.` also, I'm wondering if the new resolvers for activities have been tested at all, via postman or initializing data?

2023-04-21 04:58 UTC, markim21 commented on src/app2/schema.py
> +    def resolve_activities(self, info, name=None):
have these new resolvers been tested at all?

2023-04-21 04:58 UTC, markim21 commented on src/app2/schema.py
> +    activities = graphene.List(lambda: Activity, name=graphene.String( \
have activities been tested?

2023-04-23 05:00 UTC, snajima commented on src/app2/database.py
>      Base.metadata.drop_all(bind=engine)
Yeah, we shouldn't be dropping all the tables upon start, good catch! @markim21

2023-04-23 20:33 UTC, isabellahoie commented on src/app2/models/activity.py
> +    prices = relationship('Price', cascade='delete, all')
yup

2023-04-23 20:33 UTC, isabellahoie commented on src/app2/schema.py
> +    def resolve_activities(self, info, name=None):
yup

2023-04-23 20:34 UTC, isabellahoie commented on src/app2/schema.py
> +    activities = graphene.List(lambda: Activity, name=graphene.String( \
yu

2023-04-23 20:34 UTC, isabellahoie commented on src/app2/schema.py
> +    def resolve_activities(self, info, name=None):
using graphiql

2023-04-23 22:40 UTC, markim21 approved these changes
lgtm!

2023-04-23 22:47 UTC, merged