Implement classes model, populate model with webscraped data, enable most necessary frontend queries
cuappdev/uplift-backend pull request #101
Opened 2023-04-25 23:42 UTC by markim21

![image](https://user-images.githubusercontent.com/78518634/234400357-5cf9f01a-9759-42ad-b851-c644232341df.png)
![image](https://user-images.githubusercontent.com/78518634/234400438-65f7cc64-06c4-46e6-8306-874e0773a421.png)
![image](https://user-images.githubusercontent.com/78518634/234410108-e465d288-56f1-4caa-92df-e5219d9b9853.png)

- Create classes model with relationship to gyms
- Populate classes model by scraping from Cornell Fitness Website and adding to model 
- Tested with queries from uplift-ios codebase (particularly, ClassesAtGym, AllInstructors, AllClassNames.)

Next steps: Querying by both gym_id and date is not functional yet, as there is a problem with the way we are currently resolving DayTime and ClassTime (will fix in a separate PR)

2023-04-26 19:41 UTC, snajima requested changes
i'll review for logic a little more later but some stylistic changes for now!

2023-04-26 19:41 UTC, snajima commented on src/uplift/app.py
> +#scrape_capacity()
what's this comment for?

2023-04-26 19:41 UTC, snajima commented on src/uplift/classes_scraper.py
> +DAY_INDICES = {"Sunday": 6, "Monday": 0, "Tuesday": 1, "Wednesday": 2, "Thursday": 3, "Friday": 4, "Saturday": 5}
can we make this a global constant variable somehow?

2023-04-26 19:41 UTC, snajima commented on src/uplift/classes_scraper.py
> +                instructor = ""
some classes don't have instructors? how does this work

2023-04-26 19:41 UTC, snajima commented on src/uplift/classes_scraper.py
> +"""
function docs belong below the function header

2023-04-26 19:41 UTC, snajima commented on src/uplift/classes_scraper.py
> +    image_keyword = "General"
what is this?

2023-04-26 19:41 UTC, snajima commented on src/uplift/database.py
> +  Base.metadata.drop_all(bind=engine)
should we be dropping all?

2023-04-26 19:41 UTC, snajima commented on src/uplift/database.py
> +  scrape_classes(10)
why only 10 pages?

2023-04-26 19:41 UTC, snajima commented on src/uplift/schema.py
> +    query = query.filter(PriceModel.activity_id == self.id)
```
Price.get_query(info=info) \
   .query.filter(PriceModel.activity_id == self.id)
```

2023-04-26 19:41 UTC, snajima commented on src/uplift/schema.py
> +    date = graphene.DateTime())
spaces between and after equals sign

2023-04-26 19:41 UTC, snajima commented on src/uplift/schema.py
> +      date.day
what is this line for? `date.day`

2023-04-26 19:45 UTC, markim21 commented on src/uplift/app.py
> +#scrape_capacity()
I didn't want to scrape the website too many times, but I needed it sometimes (for when I dropped all tables) when testing. I will remove this, because we should only scrape capacity in the cron job.

2023-04-26 19:51 UTC, markim21 commented on src/uplift/database.py
> +  Base.metadata.drop_all(bind=engine)
we should not! that's my bad, I added it to test something and completely forgot to remove it. oops

2023-04-26 19:53 UTC, markim21 commented on src/uplift/database.py
> +  scrape_classes(10)
The previous codebase used a parameter of 10, so I copied that. Looking at the [website ](https://recreation.athletics.cornell.edu/fitness-centers/group-fitness-classes?_=1682538718788&page=11) it seems there are 13 pages of classes right now, but perhaps during the semester there are a minimum of 10 pages of classes? But this is shouldn't be defined in database.py, but rather in constants.py for ease of access. I'll fix that!

2023-04-26 19:55 UTC, markim21 commented on src/uplift/database.py
> +  # THESE DATETIMES ARE PURELY FOR TESTING PURPOSES AND ARE NOT ACCURATE
Ack, this was to test (this is a common theme in all of my comments, oops). I am populating the gyms model on a separate branch, but we used these datetimes to test our queries. Will take these out

2023-04-26 20:04 UTC, markim21 commented on src/uplift/schema.py
> +      date.day
unfinished code, shouldn't have been included on this PR. oops sorry :,)

2023-04-27 17:03 UTC, snajima requested changes
i don't see too many logic flaws but some things to be addressed !

2023-04-27 17:03 UTC, snajima commented on src/uplift/classes_scraper.py
> +            break
i wonder if there's a better way of doing this

2023-12-22 17:36 UTC, closed without merging