Convert to new codebase
cuappdev/uplift-backend pull request #103
Opened 2023-08-24 18:16 UTC by aldenlamp

## Overview

Clean up the codebase to represent the new version of the uplift backend. 

## Changes Made

The new version of uplift (which was previously located inside the src folder of the old version) has now been moved to the main backend. Not a lot has changed from the code perspective other than moving things around and updating requirements.

## Test Coverage

I was able to test it (launching from docker) locally to a point where I can pull up the graphql interface in my browser.

2023-08-31 16:53 UTC, Archit404Error reviewed
Only one comment here but again I'm not fully familiar with what the codebase looked like prior to this -- can you please update your PR description to be more detailed and describe what _precisely_ was moved vs deleted? It looks like certain files like scraper.py have been deleted entirely whereas others have only been moved

2023-08-31 16:53 UTC, Archit404Error commented on requirements.txt
> +pyasn1-modules==0.3.0
Are all of these version bumps and new libraries necessary -- was the requirements file out of date before?

2023-09-01 18:01 UTC, aldenlamp commented on requirements.txt
> +pyasn1-modules==0.3.0
I've added some more (hopefully clarifying) text to the PR description. Also I made a commit that updates the requirements only with those that are necessary.

2023-09-03 17:41 UTC, isabellahoie commented on app.py
> +from flask_graphql import GraphQLView
Here you have 2 lines of the same code

2023-09-03 17:52 UTC, isabellahoie commented on requirements.txt
What are all of these additions?

2023-09-03 19:35 UTC, isabellahoie commented on .dockerignore
> +Archive
What is archive?

2023-09-03 19:37 UTC, isabellahoie requested changes
Most of it looks good! Just a couple tiny things that I commented to be changed.

2023-09-04 01:31 UTC, aldenlamp commented on requirements.txt
Idt you are reviewing from the correct commit number? Archit mentioned the same concern so I made a new commit that reverts most of the changes in the requirements.

2023-09-04 01:33 UTC, aldenlamp commented on .dockerignore
> +Archive
It's just a directory that I'm using locally to make development easier for myself. I can remove it from the gitignore and move that dir somewhere else but I didn't think adding one line to the gitignore would make a difference? lmk if I should still remove it?

2023-09-11 03:06 UTC, joycrwu approved these changes
i'm also not the most familiar with what the codebase looked like prior, but generally everything looks ok with me; if bella says its good to go then all gud

2023-09-11 21:03 UTC, Archit404Error approved these changes
Good to go once you address these changes. My philosophy on constants is just to pull them all into `constants.py` and import selectively. This makes the code more readable and makes it easier to change/read all of the constants via centralization

2023-09-11 21:03 UTC, Archit404Error commented on src/constants.json
> +    "asset_base_url": "https://raw.githubusercontent.com/cuappdev/assets/master/uplift/",
I think it's better to store this in `constants.py` instead of the JSON, let's try to centralize all constants/global data in a single location.

2023-09-11 21:03 UTC, Archit404Error commented on src/database.sqlite3
Make sure to delete this file

2023-09-13 21:33 UTC, isabellahoie approved these changes
All good!

2023-09-13 21:46 UTC, merged