Add Gyms and Fitness Center hours
cuappdev/uplift-backend pull request #104
Opened 2023-08-26 22:43 UTC by aldenlamp

## Overview

Create tables relating to gyms, activities, and hours along with populating the 5 fitness center's data.

## Changes Made

### Code Removal
To keep the codebase clean, I've archived most of the implementations that were not completed and or functional at this moment (to be added back in the near future). I wanted to focus on getting the core of this backend functional (i.e. the fitness centers). Thus this PR means that the only functional part of this backend is showing the gyms and their respective fitness hours.

### Table Organization
I've rearranged the tables slightly in a way that makes more sense. Previously the Gym table represented the gym metadata (such as the location, name, description, etc.) along with the fitness center information within those (like fitness center hours). This version splits those into two parts. The Gym table (and respective object) solely represents location (recreation buildings). Within those, the fitness centers are treated as an Activity accessible at those locations. The time can be found as a property of the activities. 

An example of this is that Teagle is a gym with two Fitness Activities (Teagle Up and Teagle Down).

## Test Coverage

I tested this on my local computer (using docker and gunicorn, querying from the browser interface). 

## Next Steps (delete if not applicable)
There's a whole lotta next steps about completing the implementation of the code I removed. This includes the capacity table and its corresponding scrapers, data about other activities than just the fitness centers (along with more information such as prices and amenities), and the classes tables along with its corresponding scraper.  

There are also smaller next steps such as adding parameters to the schema and making more advanced graphql query possibilities.

2023-08-31 16:48 UTC, Archit404Error requested changes
Some logic/code changes and questions -- I'm not particularly familiar with this codebase so I'll leave the other reviewers the task of ensuring that this code integrates well with existing code

2023-08-31 16:48 UTC, Archit404Error commented on requirements.txt
> +SQLAlchemy==1.4.0
Is this a necessary bump? Generally avoid bumping dependencies because it forces all other devs to reinstall in their venv's to be up to date

2023-08-31 16:48 UTC, Archit404Error commented on dev_run_docker.sh
> +docker run -p 127.0.0.1:8000:8000/tcp uplift_backend
Change host back to 0.0.0.0 and then you can replace the port mapping to just `8000:8000`. Also generally bash scripts like this should be kept local to your dev environment, I'd suggest just creating a scripts folder (or a Makefile) where you store all these and add it into the `.gitignore`

2023-08-31 16:48 UTC, Archit404Error commented on src/constants.py
> +def _create_times(facility_id, start, end, weekday, id_base = None):
Why is this function in constants.py? I know you're hard coding values but the function itself should be in a different file -- once you are able to scrape stuff again you can just scrape the values and then call this function to ingest

2023-09-01 18:56 UTC, aldenlamp commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # Left for dev
This line of code should only be run during development which feels like it makes more sense to run locally for testing. Because we are using gunicorn (if I'm understanding it correctly), it won't run that line and gunicorn will launch on 0.0.0.0.

2023-09-01 18:57 UTC, aldenlamp commented on requirements.txt
> +SQLAlchemy==1.4.0
Good catch. It's necessary for the next PR, I just didn't separate it properly. my b.

2023-09-01 23:10 UTC, aldenlamp commented on src/constants.py
> +  # MARK: - Noyes
These represent the default data. Gym buildings and information probably won't be changing that frequently so it's probably nice to have some default data under whatever we are scraping.

2023-09-01 23:13 UTC, aldenlamp commented on src/constants.py
> +def _create_times(facility_id, start, end, weekday, id_base = None):
I feel like since at the moment all we are using is hardcoded data, and this is the only file/system that will be using this function it makes sense to keep it here for now. Once we add a scraper, we will need to rework this function anyway so it makes more sense to move it then?

2023-09-03 19:47 UTC, isabellahoie commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # Left for dev
Wait Alden can you clarify ... I am confused as to what you are saying.

2023-09-03 19:50 UTC, isabellahoie commented on src/constants.py
> +  # MARK: - Noyes
These were hardcoded from a previous semester because I was using them to test that the schema works but never intended for them to remain in the code, so we will delete them

2023-09-03 20:00 UTC, isabellahoie commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # For Dev Purposes only (use start_server.sh for release)
wait why is this necessary?

2023-09-03 20:32 UTC, isabellahoie commented on src/constants.py
> +  db_session.commit()
Are the for loops at the end ever getting called since they are outside of the create_table function

2023-09-03 20:33 UTC, isabellahoie commented on schema.graphql
> +  facilities: [Facility]
There should be an activities field in the Gyms too

2023-09-03 20:34 UTC, isabellahoie commented on schema.graphql
Activities and classes should be in the schema as well

2023-09-03 20:40 UTC, isabellahoie commented on src/models/facility.py
Why did you completely get rid of activities??

2023-09-03 20:41 UTC, isabellahoie commented on src/models/gym.py
> +    id = Column(String(40), primary_key=True)
Is this 40 for a reason?

2023-09-03 20:47 UTC, isabellahoie commented on src/models/facility.py
> +    id = Column(String(40), primary_key=True)
The data type of primary keys is usually an integer, and I think we should keep it as that

2023-09-03 20:49 UTC, isabellahoie commented on src/models/openhours.py
I like the idea of open hours, and I think it is definitely something we will keep

2023-09-03 20:53 UTC, isabellahoie commented on src/models/openhours.py
> +        }
I don't think you really need the serialize function

2023-09-03 21:03 UTC, isabellahoie commented on src/schema.py
For this one, we shouldn't get rid of activities so there are functions in here that were deleted that should still be there

2023-09-03 21:05 UTC, isabellahoie requested changes
I like some of the changes to the schema and agree that this way makes more sense, but I don't think we should just remove activities. Also, I had some other questions that I left in there

2023-09-04 01:39 UTC, aldenlamp commented on src/constants.py
> +  db_session.commit()
They are inside the function. This is a function that isn't inside of a class so its only one indent in.

2023-09-04 01:54 UTC, aldenlamp commented on src/models/facility.py
Hey, I see a lot of mention about the activities and the classes in separate comments so I'm going to just address all of that in this comment thread and resolve those (we can talk more abt those things here). 

I want to clarify, my approach/mindset to activities and classes was not like a 'lmao remove it because it's not necessary and we should get rid of it'; it's mainly about development order. My whole objective was the keep the Uplift repository/codebase clean. In my opinion, the only things that should exist on the master branch are those that are fully functional, useable, and able to be pushed to release immediately (noting that we will soon implement an auto-release feature). 

As of the current state of the master branch, the activities schema was intact with no functionality to populate or scrape the data (which In my mind means it should not yet be merged into the master branch) and there was no development around classes yet. What should happen (IMO) is once those are completed as whole units of functionality, there should be separate PR's to merge them in. 

From my understanding, there are two branches that are currently active that represent those groupings of functionalities (activities and classes). The code in those branches, once fully completed, should add the changes relating to adding activities and classes. Side note: I think those branches should probably be rebased on top of these PRs (or whatever ultimately gets merged into master).

2023-09-04 01:57 UTC, aldenlamp commented on src/models/openhours.py
> +        }
Yeah I agree, I don't think it's really necessary. It's been helpful for me for testing and debugging so I left it in. I can get rid of it if you would like?

2023-09-04 01:57 UTC, aldenlamp commented on src/schema.py
See above response.

2023-09-04 02:08 UTC, aldenlamp commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # Left for dev
Yeah, ofc. The docker container is configured to run the start_server.sh file. Inside that file, we use gunicorn as the way to launch/start the server so we can have multiple threads receiving requests in case there is high traffic. I'm not entirely sure how gunicorn does its thing, but I know that it does not run app.py as '__main__' and I know that it has its own way of setting up IPs and ports. Thus, when we are actually running the server (like properly with docker and everything), the 'if __name__ == __main__' will not fire and so those parameters are meaningless (you can look in start_server.sh to see the actual parameters we are using). 

Thus, the only time that code gets run will be when a developer runs 'python app.py' on their command line (I can't think of any other reason than for testing and development). And to me, it makes more sense to have testing and development launch on localhost. 

Side note: the iOS app has already been configured (probably from a long time ago) to switch its routing to localhost when in development mode. This kinda feels like the analogous from the backend perspective.

2023-09-04 02:08 UTC, aldenlamp commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # For Dev Purposes only (use start_server.sh for release)
see above

2023-09-04 02:09 UTC, aldenlamp commented on src/models/gym.py
> +    id = Column(String(40), primary_key=True)
Yeah, the keys are generated as hashes of the gym names. The hash comes out to be 40 characters.

2023-09-04 15:10 UTC, Archit404Error commented on src/constants.py
> +def _create_times(facility_id, start, end, weekday, id_base = None):
Seems like hardcoded data will be removed so would make sense to move this

2023-09-04 15:13 UTC, Archit404Error commented on app.py
> +    app.run(host="127.0.0.1", port=5000) # Left for dev
This is kind of an irrelevant change since either 127.0.0.1 or 0.0.0.0 would work locally and would both show up on localhost, it's just a matter being accessible via machine IP address, you can go ahead and change it if you'd like though

2023-09-04 15:19 UTC, Archit404Error commented on src/models/facility.py
I'm not entirely sure what the state of activities was so I'll leave the technical decision for this up to Bella. Regardless, I'd say that in the future when you're making large changes like this they should definitely be discussed beforehand because otherwise we run into situations where technical decision may have to be reverted.

Also, when you make large changes like removing activities, you should generally specify in the PR -- I personally was pretty confused about this since the PR description says "created tables relating to activities"

2023-09-04 16:14 UTC, aldenlamp commented on src/models/facility.py
Yeah, that's valid. We did kinda discuss this stuff. I think by the end of our discussion we were on the same page about what the backend will look like (schema wise). I think the only thing we didn't really discuss was branch management and how to organize getting there (like if activities should be in this PR or a next one). 

About the PR description, that was my mistake. I meant to say facilities but I wrote activities instead. sorry bout that.

2023-09-06 01:26 UTC, isabellahoie approved these changes
Looks good to me! :)

2023-09-06 01:29 UTC, Archit404Error approved these changes
Good to go once you remove the sqlite3 files

2023-09-06 04:09 UTC, joycrwu approved these changes

2023-09-11 20:47 UTC, merged