Update capacity scraper
cuappdev/uplift-backend pull request #105
Opened 2023-08-28 18:35 UTC by aldenlamp

## Overview

This adds back the capacity table along with a scraper that pulls capacity from the CFC website.

## Changes Made

There are a few notable changes. 
* Capacities are now a table related to the facility (seeing as there are fitness centers and courts in the same gyms that have capacities). 
* The scraper is now run as an isolated process outside the flask server (see start_server.sh). This way, when using gunicorn there is only one scraper instead of however many there are with gunicorn threads. 
* Scraper now pulls from the CFC bar chart instead of the circle chart so we can scrape the percent as well as the count. 

## Test Coverage

I tested it locally on my computer. I let it sit for a few minutes to see and make sure that when the CFC site gets updated the graphql endpoints return the correct and most recent capacity. 

## Next Steps

Maybe we should think about switching from SQLite soon so we can save the capacities now and do data analytics in the future. Either that or some effective way of persisting the data beyond the SQLite in the docker container.

2023-09-06 01:37 UTC, isabellahoie commented on src/models/capacity.py
> +  facility_id = Column(String(40), ForeignKey('facility.id'), nullable=False)
The facility id should be an integer not a string

2023-09-06 01:38 UTC, isabellahoie commented on src/models/capacity.py
> +  id = Column(Integer, Identity(1, 1), primary_key = True)
We don't need Identity(1, 1) here

2023-09-06 01:40 UTC, isabellahoie commented on src/models/facility.py
> +    basketball = 1
Pleasee remove basketball

2023-09-06 01:55 UTC, isabellahoie commented on start_server.sh
> +python c2c_scraper.py
put it in the dockerfile

2023-09-09 05:12 UTC, isabellahoie commented on c2c_scraper.py
> +      if not (Capacity.query.filter(and_(Capacity.facility_id==facility_id, Capacity.updated==last_updated)).first()):
should we delete the old ones we do not need anymore or is it worth it to keep them all?

2023-09-09 05:14 UTC, isabellahoie requested changes
Overall, this looks good to me other than the small comments I left!

2023-09-11 22:50 UTC, aldenlamp commented on start_server.sh
> +python c2c_scraper.py
I marked it with a TODO.

2023-09-11 22:51 UTC, aldenlamp commented on c2c_scraper.py
> +      if not (Capacity.query.filter(and_(Capacity.facility_id==facility_id, Capacity.updated==last_updated)).first()):
Yeah, It will be good to run data analytics on it in the future. Generate the popular graph instead of hardcoding it.

2023-09-12 20:45 UTC, Archit404Error requested changes
Solid work, here are some suggestions to clean up the code

2023-09-12 20:45 UTC, Archit404Error commented on c2c_scraper.py
> +RECTRAC_PATH = "https://rectrac.pe.cornell.edu/private/webtrac.wsc/history.html?historyoption=inquiry&_csrf_token=9e7d41b4de08bca17c1e7b304c9bae559c02e92712476c3dcb8d0b342f6afeac"
Rebase onto the branch in which I had you factor these out, or merge those changes in if this wasn't branched off that

2023-09-12 20:45 UTC, Archit404Error commented on c2c_scraper.py
> +    percent = -1 if lines[4] == "NA" else (int(lines[4][:-1]) / 100)
I know you have comments here but it's still pretty unclear what exactly `lines[0]`, `lines[1]`, etc actually hold at a first glance. One way you can get around this issue is to create a wrapper class, which will take in a line and produce an object with named attributes, a really simple one-liner to do this is via [NamedTuple](https://docs.python.org/3/library/collections.html#collections.namedtuple).

2023-09-12 20:45 UTC, Archit404Error commented on c2c_scraper.py
> +    time.sleep(60) # Currently scrapes every minute
This seems way too often, you'll likely want to scrape once every hour or something -- what rate does the site update at?

Also, pull out this magic sleep constant into `constants.py`

2023-09-12 21:03 UTC, aldenlamp commented on c2c_scraper.py
> +    time.sleep(60) # Currently scrapes every minute
I've changed it to once every five minutes. I think they update it at arbitrary times (although I was told they try to target once every 15 minutes). I think we should keep it scraping relatively frequently seeing as this capacity can change dramatically in a very short amount of time.

2023-09-12 21:32 UTC, Archit404Error approved these changes
Good to go once you address these comments

2023-09-12 21:32 UTC, Archit404Error commented on c2c_scraper.py
> +    capacity_data = CapacityRawData(*list(map(str.strip, filter(lambda v: v != '', gymData.get_text("\n").split("\n")))))
This one liner is now extremely unreadable, I'd prefer if this were expanded out into a for loop (or at the very least pulled out into a 2-liner)

2023-09-12 21:32 UTC, Archit404Error commented on src/constants.py
> +CAPACITY_SCRAPE_INTERVAL = 5 # In minutes
Generally it's good to incorporate the unit in the constant name, so `CAPACITY_SCRAPE_INTERVAL_MINUTES` is a better naming strategy here than the current name + a comment. Also, let's maybe bump this to 15 for now, I think this is how often course grab was pinging and our server got IP banned

2023-09-13 21:37 UTC, joycrwu commented on src/schema.py
> +  def resolve_gyms(self, info):
do we not use name as an input anymore

2023-09-13 21:37 UTC, joycrwu approved these changes
all gud, just had a small clarifying question

2023-09-13 21:45 UTC, isabellahoie approved these changes
Looks good to me

2023-09-13 21:45 UTC, isabellahoie commented on src/schema.py
> +  def resolve_gyms(self, info):
this is fine for now

2023-09-13 21:47 UTC, merged