Create Classes model
cuappdev/uplift-backend pull request #109
Opened 2023-09-24 20:47 UTC by kidzegeye

## Overview

Created the Classes model for storing group classes

## Changes Made

* Created Classes model, with a many-to-many relationship with Gyms

## Next Steps (delete if not applicable)

* Create the webscraper for the classes

2023-09-25 02:31 UTC, joycrwu commented on src/models/classes.py
> +        back_populates="classes",  ##Change gym to rec_center
prob remove the comment

2023-09-25 02:31 UTC, joycrwu approved these changes
other than the small comment looks gud!

2023-09-25 23:11 UTC, isabellahoie commented on src/models/price.py
> +from database import Base
Wait why were prices added into this PR? Do we need prices for classes?

2023-09-25 23:13 UTC, isabellahoie requested changes
Just the changes Joyce requested and then my question at the bottom

2023-09-25 23:17 UTC, isabellahoie commented on src/models/price.py
> +    def __init__(self, **kwargs):
missing self.id in init

2023-10-01 15:43 UTC, kidzegeye commented on src/models/price.py
> +from database import Base
I removed it

2023-10-04 20:03 UTC, isabellahoie approved these changes
Looks good to me

2023-10-04 21:25 UTC, merged