Refactored models, added Google Sheets scraping
cuappdev/uplift-backend pull request #119
Opened 2023-12-27 04:35 UTC by vinnie4k

## Overview

Refactored the entire backend to work with a Google Sheets scraper.

## Changes Made

- Updated the schema with fields that are more usable and frontend friendly. See “New Schema” section below.
- Replace the old `constants.json` file with new constants.
- When `app.py` runs for the first time (a new Docker container is built), all tables in the database are dropped. This keeps our database clean and fresh since all data will be inserted again.
    - Note that if we plan on storing user data at some point, we may not want to drop all tables.
- Added proper documentation to all of our models as well as scraping functions.
- Removed old scraper files. We will be creating a new “microservice” codebase that will web scrape into the Google Sheets. This codebase only handles Google Sheets scraping.
- Wrote test cases for scraper helper functions.
    - Simply run `python -m unittest src.tests.test_scraper` to run the test suite.
- Removed all files in the `uplift` folder we had originally. I believe all of this was deprecated.
- Set a schedule to scrape from the Google Sheets every 10 minutes.
- Updated `README` with new secrets and setup instructions.

### Notes

- Morrison building hours is the same as its fitness center hours since there are no other facilities.
- The “ALT” marker for court hours means that it alternates depending on the day of the week (HNH Court 2).

## Next Steps

- Implement activities for a Gym.
- Implement classes for a Gym.
- Implement equipment for a Facility.
- Implement HNH bowling hours.
- Double check amenities in `constants.json`.
- Not sure if we need to change the `Dockerfile` to make the container run in Eastern time. I wrote the code to handle it but we’ll see.
- Set up staging environment (dev and prod server).
    - Will need to change the code up a bit.
- Set up Google Sheets scraping for special hours.
    - Will need to do some overriding.

## New Schema

### Gym

- `id: Int` The ID of this gym (building).
- `address: String` The address of the building.
- `amenities: [Amenity]?` This gym’s amenities.
- `facilities: [Facility]?` This gym’s facilities.
- `hours: [OpenHours]?` The building hours.
- `image_url: String` The URL of this gym's image.
- `latitude: Float` The latitude coordinate of this gym.
- `longitude: Float` The longitude coordinate of this gym.
- `name: String` The name of this gym.

### Facility

- `id: Int` The ID of this facility.
- `capacity: Capacity?` The capacity of this facility.
- `facility_type: FacilityType` The type of this facility.
    - `FITNESS` Fitness Center.
    - `POOL` Swimming Pool.
    - `BOWLING` Bowling Alley.
    - `COURT` Basketball Court.
- `gym_id: Int` The ID of the gym this facility belongs to.
- `hours: [OpenHours]?` The hours of this facility.
- `name: String` The name of this facility.

### Capacity

- `id: Int` The ID of this capacity.
- `count: Int` The number of people in this facility.
- `facility_id: Int` The ID of the facility this capacity belongs to.
- `percent: Float` The percent filled between 0.0 and 1.0.
- `updated: Int` The Unix time since this capacity was last updated.

### OpenHours

- `id: Int` The ID of these hours.
- `court_type: CourtType?` The type of this court for these hours, if applicable.
- `end_time: Int` The Unix time of when this facility closes for this day.
- `facility_id: Int?` The ID of the facility for these hours, if applicable.
- `gym_id: Int?` The ID of the gym for these hours, if applicable.
- `is_shallow: Bool?` True if these hours are for shallow waters only (only applicable for pool hours hence nullable).
- `is_women: Bool?` True if these hours are for women only (only applicable for pool hours hence nullable).
- `start_time: Int` The Unix time of when this facility opens for this day.

### Amenity

- `id: Int` The ID of this amenity.
- `gym_id: Int` The ID of the gym with this amenity.
- `type: AmenityType?` The type of this amenity such as showers, lockers, etc.
    - `SHOWERS` Showers.
    - `LOCKERS` Lockers.
    - `PARKING` Parking Lot.
    - `ELEVATORS` Elevators/Lifts.

## Screenshots

- Run the sample query below in the GraphQL playground.
<img src="https://github.com/cuappdev/uplift-backend/assets/75594943/40921823-7cfe-43cd-a6f8-c9b5ed163000" width="300" height="auto"/>
<img src="https://github.com/cuappdev/uplift-backend/assets/75594943/d1195447-f53e-4654-b92b-bafd944b2b92" width="300" height="auto"/>

## Sample Query

```
fragment capacityFields on Capacity {
  count
  percent
  updated
}

fragment openHoursFields on OpenHours {
  courtType
  endTime
  isShallow
  isWomen
  startTime
}

fragment facilityFields on Facility {
  id
  capacity {
    ...capacityFields
  }
  facilityType
  hours {
    ...openHoursFields
  }
  name
}

fragment gymFields on Gym {
  id
  address
  amenities {
    type
  }
  facilities {
    ...facilityFields
  }
  hours {
    ...openHoursFields
  }
  imageUrl
  latitude
  longitude
  name
}

query GetAllGyms {
  gyms {
    ...gymFields
  }
}
```

2023-12-31 16:52 UTC, Archit404Error requested changes
Thanks again for taking the time to work on this Vin! Changes look great overall, I've left some suggestions that should hopefully clean up the code and make it easier to maintain in the future.

Other than the changes made here, my main question is (@joycrwu feel free to answer these as well if you know):
- How is the backend deployed currently? The docker file doesn't seem to actually run the server and there's no compose, so did we deploy manually?

You should test this but as I said below I think the `time.sleep()` for the scraper pauses the main thread and reduces our backend's performance so we should ideally deploy the scraper separately.

Once you've addressed these changes feel free to re-request and I'll re-review!

2023-12-31 16:52 UTC, Archit404Error commented on src/models/facility.py
> +    name = Column(String(1000), nullable=False)
The length parameter is optional for SQLAlchemy `String` so might as well remove it since 1000 seems like an arbitrary limit. Same goes for the other string columns.

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/capacities_scraper.py
> +    noyes_court = vals[9][1:]
Although your variable names are descriptive it's still kind of hard to understand what the right side of the assignments mean because they're dependent on what the spreadsheet looks like.

A good way to get around this might be to wrangle the values into a Pandas DataFrame, which might make the code look a bit more readable -- see if you can get this to work, if not then you can use NamedTuple for each of these values as described below

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/capacities_scraper.py
> +        updated = get_capacity_datetime(rows[i][2])
If you choose not to go with the DataFrame approach, a nice way to clean this up without having to memorize which index corresponds to which value is to use Python's [NamedTuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) class to create a simple wrapper class for each row's values that will make each of these entries a named attribute, simplifying the code.

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +    morrison = vals[5][1:]
Same comment about the DataFrame/NamedTuple

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/capacities_scraper.py
> +    db_session.commit()
I think maybe instead of passing in the facility id directly into this function you could just pass in the facility name since they al have unique names anyway and then fetch the id based on the facility name for use in the capacity creation. This way you don't have to store a giant dict of facility names to ids since if we ever added a new facility or deleted a facility we'd have to update that map in addition to the database.

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +            GYM_ID_DICT["morrison"],
Same comment about the facility dict for the gym id dict here, since each gym should have a unique name you can just fetch the id from the DB instead of hardcoding

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +        morr=vals[FACILITY_ROW_DICT["fc_morr"]][2:],
Same comment about NamedTuple for all the data in `vals[FACILITY_ROW_DICT["<facility>"]][2:]`

2023-12-31 16:52 UTC, Archit404Error commented on src/utils/constants.py
> +}
I'd suggest removing this and instead just having some helper functions to fetch ids from the DB given a facility name. This is clearly a 1-1 mapping seeing as we're already storing it in a dict so I'm assuming this means two distinct facilities will never have the same name. Storing the dict here thus duplicates data and makes it harder to do any updates to the DB (ex. deleting or adding a new facility) since we'll have to remember to update this mapping.

2023-12-31 16:52 UTC, Archit404Error commented on src/utils/constants.py
> +    "fc_hnh": 3 - FACILITY_ROW_OFFSET,
Is there a reason we're storing `3 - FACILITY_ROW_OFFSET` here instead of just storing `2`?

2023-12-31 16:52 UTC, Archit404Error commented on src/utils/constants.py
> +GYM_ID_DICT = {"hnh": 1, "morrison": 2, "noyes": 3, "teagle": 4}
Same comment as `FACILITY_ID_DICT` here

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +        time_strings = [hnh[weekday], teagle[weekday]]
Instead of hardcoding that HNH and Teagle are the only facilities with pools, can we make the schema more expressive to capture this? We can then auto fetch all facilities with pools here instead of hardcoding this

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +    """
Again, why pass in separate values for each fitness center instead of just all the data directly? If Cornell ever built a new gym or shut one down we'd have to modify this function's parameters and its logic, whereas if we just pass in all gym data directly we wouldn't have to change anything

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +    """
Same comment here as below on changing the schema to capture which gyms have courts and then fetching that data instead of hard coding the gyms

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/reg_hours_scraper.py
> +    """
Same comment here as below about changing schema to express which gyms have bowling and then fetching them instead of hard coding

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/sp_hours_scraper.py
> +            time_strings = row[3:]
Same comment about NamedTuples

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/scraper_helpers.py
> +    - Returns:      An array containing three elements.
```suggestion
    - Returns:      An array containing four elements as described above.
```

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/scraper_helpers.py
> +    fourth is shallow only (bool).
Again I'd suggest using NamedTuple here to make these attributes and avoid having to write this in the spec

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/scraper_helpers.py
> +    - Returns:      An array containing three elements.
Same suggestion about NamedTuple, you can unpack NamedTuples the same way you unpack tuples

2023-12-31 16:52 UTC, Archit404Error commented on src/scrapers/sp_hours_scraper.py
> +    day_end_unix = day_start_unix + 86400  # 86400 seconds in a day
I'd suggest storing `86400` in `constants.py` to avoid the comment

2023-12-31 17:46 UTC, vinnie4k commented on src/constants.json
> +    ],
Correct.

2023-12-31 17:51 UTC, vinnie4k commented on src/models/amenity.py
> +    def __init__(self, **kwargs):
It was like this before, and I believe it's pretty conventional on AppDev at least. It's a lot cleaner and when you have many arguments it can get difficult to track.

2023-12-31 18:12 UTC, vinnie4k commented on src/utils/constants.py
> +}
Yea, that was my original plan, but after looking at the design, there are facilities with the same names. For example, the pools for Teagle and Helen Newman are called "Swimming Pool". When I implemented the frontend, I made the title of these cells the name of the facility which could be the same for multiple.

2023-12-31 18:15 UTC, vinnie4k commented on src/utils/constants.py
> +    "fc_hnh": 3 - FACILITY_ROW_OFFSET,
My reasoning was because the row number is "3" in the sheets but since Python lists are zero-indexed, there is an offset.  This "3" makes it more clear to the developer that it's in row 3 on the sheet.

2023-12-31 19:09 UTC, joycrwu commented
> * How is the backend deployed currently? The docker file doesn't seem to actually run the server and there's no compose, so did we deploy manually?

yup, the backend is manually deployed right now, we just spin up the docker-compose on the server itself

2023-12-31 22:24 UTC, vinnie4k commented on src/utils/constants.py
> +}
Nevermind, the backend code looks a lot cleaner if the names are unique. I can just handle this on frontend.

2024-01-01 00:24 UTC, vinnie4k commented on app.py
> +    time.sleep(60)
I'm pretty sure it stops the execution of the current thread only and not the entire program. https://www.digitalocean.com/community/tutorials/python-time-sleep

2024-01-01 00:27 UTC, vinnie4k commented
> Thanks again for taking the time to work on this Vin! Changes look great overall, I've left some suggestions that should hopefully clean up the code and make it easier to maintain in the future.
> 
> Other than the changes made here, my main question is (@joycrwu feel free to answer this as well if you know):
> 
> * How is the backend deployed currently? The docker file doesn't seem to actually run the server and there's no compose, so did we deploy manually?
> 
> You should test this but as I said below I think the `time.sleep()` for the scraper pauses the main thread and reduces our backend's performance so we should ideally deploy the scraper separately.
> 
> Once you've addressed these changes feel free to re-request and I'll re-review!

Yea, I tested everything locally and wrote my frontend code with the local backend. We can check for performance issues once it's actually deployed to our servers which I believe we do it manually since there isn't a compose file.

2024-01-06 19:10 UTC, Archit404Error approved these changes
Good to go

2024-01-06 20:55 UTC, merged