Created Activities and Gear models
cuappdev/uplift-backend pull request #143
Opened 2024-03-22 21:24 UTC by daisychangm

## Overview

Added activities model for the activities feature. Added gear model for gear associated with each activity.

## Changes Made

Created a new file (activity.py) containing the activities and gear model. The Activity class contains its name, the id of the facility it corresponds to, the id of the gym that it corresponds to, its price, whether or not it requires reservations, and the gear required. The Gear class contains its name, price, and the id of the activity it corresponds to. The two reflect a one-to-many relationship. The required queries were also added to schema.py.

## Test Coverage

This feature was manually tested using the graphQL playground. No errors arose, and the appropriate fields were reflected correctly.

## Next Steps

Create a web scraper to populate the models with data.

2024-03-22 21:47 UTC, kidzegeye requested changes
Looking good! Made a few comments to address

2024-03-22 21:47 UTC, kidzegeye commented on .python-version
Not sure what this file is for, can you exclude this from your PR?

2024-03-22 21:47 UTC, kidzegeye commented on src/models/activity.py
> +    facility_id = Column(Integer, nullable=False)
Is this not a foreign key as well?

2024-03-22 21:47 UTC, kidzegeye commented on src/models/activity.py
> +        self.needs_reserve = kwargs.get("needs_reserve")\
Remove the \ at the end of the line

2024-03-22 21:47 UTC, kidzegeye commented on src/models/gym.py
> +    activities = relationship("Activity")
Might need to also add this to the Facility model

2024-03-23 16:03 UTC, daisychangm commented on src/models/gym.py
> +    activities = relationship("Activity")
Done!

2024-03-25 00:22 UTC, vinnie4k requested changes
Great job on your PR Daisy! Overall, these changes were solid but there are a few comments I would like to point out:
- Let's get Black formatting installed so that your files can be properly formatted.
- Documentation consistency is important. This includes punctuation, capitalization, etc.
- Keeping things alphabetized is a common convention developers use so let's follow that as well.

In your next PR, make sure to include a screenshot of the query results from the playground in the PR description. We also can't really test this until your scraper is implemented so that it can populate the database, but it should be good for now. It'll be easier to figure out if there are any changes that need to be made once you begin implementing the scraper.

Once you have addressed my comments, feel free to request me again.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/activity.py
> +        - `one_time_price`  The one-time price of this activity.
For consistency, let's follow the same format as `need_reserve` since these are both booleans.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/activity.py
> +        - `gear`            (nullable) This activity's gear.
These should be sorted alphabetically with the exception of `id`.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/activity.py
> +        }
Same as above with the alphabetical ordering.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/activity.py
> +    - `activity_id`     The ID of the activity this gear belongs to
Let's add a period to the end for consistency purposes. Same thing with the indentation of the attributes. These should also be alphabetize.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/activity.py
> +        }
Same as above with the alphabetical ordering.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/facility.py
> +        - `activities`      (nullable) The activities of this facility
Nice job adding these. Put these in alphabetical order too.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/facility.py
> +    activities = relationship("Activity")
Same as above.

2024-03-25 00:22 UTC, vinnie4k commented on src/models/gym.py
> +        - `activities`      (nullable) The gym's activities.
Same as above.

2024-03-26 06:39 UTC, vinnie4k approved these changes
Good to go. Great job!

2024-03-27 14:12 UTC, kidzegeye approved these changes
Looks good to me

2024-04-10 22:09 UTC, merged