Add User and Giveaway models
cuappdev/uplift-backend pull request #144
Opened 2024-03-24 04:09 UTC by sophiestrausberg

## Overview
Added User model and Giveaway model.

## Changes Made

Created `user.py` and `giveaway.py` to define the User and Giveaway models respectively. The models are related with a one-to-many relationship, where one giveaway can have many users. The User model stores a user's net id and an optional giveaway id. The Giveaway model stores the giveaway's name and the list of users it corresponds to. Updated `schema.py` to include necessary queries and an additional query for retrieving all users with a particular giveaway id. Implemented support for mutations, though functioning mutations haven't been implemented yet.

## Test Coverage

Manually tested the feature in the GraphQL playground. Found no errors.

## Next Steps (delete if not applicable)

Implement mutation to create a new user. Integrate user authentication through Duo.

2024-03-24 22:08 UTC, vinnie4k requested changes
Great job on your first PR Sophie! Overall, looks very solid but there are a few comments:
- It looks like you don't have Black formatter installed. Can you get that set up and reformat all of your files?
- We should separate the current mutation that creates a user into two, where one of it would be for entering a giveaway.
- It's always good to clean up your import statement at the top and remove unused imports.
- The `User` model in SQL should contain a list a giveaway IDs, and the `Giveaway` model should contain a list of user IDs. You would need a joint table for this.

Once you have resolved these comments (make sure to mark them as resolved on GitHub), feel free to request my aftewards.

2024-03-24 22:08 UTC, vinnie4k commented on src/models/user.py
> +    giveaway_id = Column(Integer, ForeignKey("giveaway.id"), nullable=True)
```suggestion
    giveaway_ids = relationship("Giveaway")
```

2024-03-27 22:08 UTC, kidzegeye commented on schema.graphql
> +  createUser(giveawayId: Int, netId: String): createUser
^^^

2024-04-09 20:50 UTC, vinnie4k requested changes
Great job addressing the changes Sophie! Because we are a bit short on time, I gave you the refactored code instead of just giving you comments. Not 100% sure that it works, but you should definitely test it.

After this PR gets merged, we should refactor the codebase to remove unused code and add descriptions to the GraphQL models for API specs. We should also rename `GiveawayInstance` to `GiveawayUsers` or `GiveawayEntry` to make it more clear that it's an association table, but for the sake of time, we can leave it for now.

You can use the following GraphQL code to test:
```graphql
fragment userFields on User {
  id
  netId
  giveaways {
    id
    name
  }
}


fragment giveawayFields on Giveaway {
  id
  name
  users {
    ...userFields
  }
}

query GetUsersByGiveawayId($id: Int) {
  getUsersByGiveawayId(id: $id) {
    ...userFields
  }
}

mutation CreateUser($netId: String!) {
  createUser(netId: $netId) {
    user {
      ...userFields
    }
  }
}

mutation EnterGiveaway($giveawayId: Int!, $userNetId: String!) {
  enterGiveaway(giveawayId: $giveawayId, userNetId: $userNetId) {
    giveawayInstance {
      id
      userId
      numEntries
    }
  }
}

mutation CreateGiveaway($name: String!) {
  createGiveaway(name: $name) {
    giveaway {
      ...giveawayFields
    }
  }
}
```
Inside of Graph iQL (the playground), you can add query variables (at the bottom) to be passed in. For example, to create a giveaway, you can define the following query variables:
```
{
  "name": "Some giveaway name"
}
```

2024-04-09 20:50 UTC, vinnie4k commented on src/models/giveaway.py
> +        - `user_ids`        (nullable) The IDs of users entered into this giveaway.
```suggestion
        - `users`           (nullable) The users that entered into this giveaway.
```

2024-04-09 20:50 UTC, vinnie4k commented on src/models/giveaway.py
> +        return {"id": self.id, "name": self.name, "user_ids": self.user_ids}
```suggestion
    users = relationship("User", secondary="giveaway_instance", back_populates="giveaways")
```

I just realized that `serialize` isn't used for anything so we could probably remove it (we should remove it for the other models as well). I'm pretty sure we can also remove the initializer too.

When using an association table, you want to use `secondary`. See the change above.

2024-04-09 20:50 UTC, vinnie4k commented on src/models/giveaway.py
> +    giveaways = relationship("User", back_populates="giveaway_ids")
```suggestion
    num_entries = Column(Integer, nullable=False)
```
We don't need a column for `users` and `giveaways` in the association table. Change `numEntries` to snake_case.

2024-04-09 20:50 UTC, vinnie4k commented on src/models/user.py
> +        - `giveaway_id`     (nullable) The list of giveaways a user is entered into.
```suggestion
        - `giveaways`       (nullable) The list of giveaways a user is entered into.
```

2024-04-09 20:50 UTC, vinnie4k commented on src/models/user.py
> +    giveaway_ids = relationship("GiveawayInstance", back_populates="giveaways")
```suggestion
    giveaways = relationship("Giveaway", secondary="giveaway_instance", back_populates="users")
```

Same thing as mentioned above, we want to use `secondary` here.

2024-04-09 20:50 UTC, vinnie4k commented on src/models/user.py
> +        return {"id": self.id, "net_id": self.net_id, "giveaway_id": self.giveaway_id}
```suggestion
```
We can probably remove this. We should also refactor the rest of the codebase later.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +        return query
```suggestion
```
We don't need this.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +    users_by_giveawayid = graphene.List(User, id=graphene.Int())
```suggestion
    get_all_gyms = graphene.List(Gym, description="Get all gyms.")
    get_users_by_giveaway_id = graphene.List(User, id=graphene.Int(), description="Get all users given a giveaway ID.")
```

Frontend will need to refactor a bit but because these are also field resolvers, it's a lot more clear to prepend them with "get". When I was working on Volume, this was the convention and it makes it a lot more clear. We should also add a description since Graph iQL can use this for documentation purposes. See the screenshot below. Also, add an underscore in `giveawayid` so that GraphQL can convert this to camelCase.

<img width="341" alt="image" src="https://github.com/cuappdev/uplift-backend/assets/75594943/c08c69f1-912e-4fee-a855-45bcc011b6d4">

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
>      def resolve_gyms(self, info):
```suggestion
    def resolve_get_all_gyms(self, info):
```

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +    return query.all()
```suggestion
    def resolve_get_users_by_giveaway_id(self, info, id):
        entries = GiveawayInstance.get_query(info).filter(GiveawayInstanceModel.giveaway_id == id).all()
        users = [User.get_query(info).filter(UserModel.id == entry.user_id).first() for entry in entries]
        return users
```
This should be indented. You can also change the way you're filtering to make it more time efficient.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +        net_id = graphene.String()
```suggestion
        net_id = graphene.String(required=True)
```

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +        return CreateUser(user=new_user)
```suggestion
    def mutate(root, info, net_id):
        # Check to see if NetID already exists
        existing_user = User.get_query(info).filter(UserModel.net_id == net_id).first()
        if existing_user:
            raise GraphQLError("NetID already exists.")

        # NetID does not exist
        new_user = UserModel(net_id=net_id)
        db_session.add(new_user)
        db_session.commit()
        return CreateUser(user=new_user)
```

Let's keep the querying consistent and avoid using the query function from the DB session. You also want to add proper error handling so that frontend can process the errors. You can simply raise a `GraphQLError` and pass in a string with the error message. Make sure to import it using `from graphql import GraphQLError`.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +    success = graphene.Boolean()
```suggestion
```
We should remove this and throw errors instead.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +        return EnterGiveaway(success=True, giveaway_instance=giveaway_instance)
```suggestion
    def mutate(self, info, user_net_id, giveaway_id):
        # Check if NetID and Giveaway ID exists
        user = User.get_query(info).filter(UserModel.net_id == user_net_id).first()
        if not user:
            raise GraphQLError("User with given NetID does not exist.")

        giveaway = Giveaway.get_query(info).filter(GiveawayModel.id == giveaway_id).first()
        if not giveaway:
            raise GraphQLError("Giveaway does not exist.")

        # Compute number of entries
        giveaway_instance = (
            GiveawayInstance.get_query(info)
            .filter(GiveawayInstanceModel.giveaway_id == giveaway_id)
            .filter(GiveawayInstanceModel.user_id == user.id)
            .first()
        )
        if not giveaway_instance:
            # Giveaway does not exist
            giveaway_instance = GiveawayInstanceModel(user_id=user.id, giveaway_id=giveaway_id, num_entries=1)
            db_session.add(giveaway_instance)
        else:
            # Giveaway exists
            giveaway_instance.num_entries += 1

        db_session.commit()
        return EnterGiveaway(giveaway_instance=giveaway_instance)
```

Since we are on a time crunch, I refactored your logic. A few things I want to point out:
1. We want to avoid querying with `db_session`.
2. We should throw an error for better frontend processing.
3. Your code does not support increasing the number of entries if the user has already entered the giveaway.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +
```suggestion


class CreateGiveaway(graphene.Mutation):
    class Arguments:
        name = graphene.String(required=True)

    giveaway = graphene.Field(Giveaway)

    def mutate(self, info, name):
        giveaway = GiveawayModel(name=name)
        db_session.add(giveaway)
        db_session.commit()
        return CreateGiveaway(giveaway=giveaway)
```
We should create a mutation to create a giveaway. This should also allow you to test without having to write a SQL query in the DB directly.

2024-04-09 20:50 UTC, vinnie4k commented on src/schema.py
> +    enterGiveaway = EnterGiveaway.Field()
```suggestion
    create_giveaway = CreateGiveaway.Field(description="Creates a new giveaway.")
    create_user = CreateUser.Field(description="Creates a new user.")
    enter_giveaway = EnterGiveaway.Field(description="Enters a user into a giveaway.")
```

2024-04-10 18:21 UTC, vinnie4k approved these changes
Just one small thing and it's good to me! I did some testing and it looks solid. Really great work Sophie! In the future, I would avoid creating a commit with the suggestion feature for every suggestion because my suggested code might be wrong, and we wouldn't want to commit that 😅.

Let's wait for another approval before merging.

2024-04-10 18:21 UTC, vinnie4k commented on src/models/giveaway.py
> +        - `numEntries`         The number of entries of this user into the giveaway.
```suggestion
        - `num_entries`        The number of entries of this user into the giveaway.
```

2024-04-10 22:06 UTC, kidzegeye approved these changes
lgtm!

2024-04-11 17:54 UTC, isabellahoie approved these changes
looks good to me! :)

2024-04-12 05:35 UTC, merged