Marya/capacity
cuappdev/uplift-backend pull request #99
Opened 2023-04-15 20:41 UTC by markim21

## Overview

- Add capacity model and scraper for C2C website. Also include a cron job
- Merge the work I did remotely (because I did not have access to github or the internet while working on this) with bella's gym models

## Test Coverage

Manually tested this using the following query:
![image](https://user-images.githubusercontent.com/78518634/232252304-00b51a2a-a5da-4962-b283-b8f1b4186329.png)

## Next Steps (delete if not applicable)

- Remove app folder (with deprecated features) 
- Start running cron job (after it is reviewed by someone) 
- Finish all queries for frontend

2023-04-16 20:16 UTC, snajima requested changes
AMAZING work with the web scraper marya 🎉 !! just a few slight changes, and also do you mind renaming your PR to [action verb] [description of feature], like "Implemented web scraper for capacity"

2023-04-16 20:16 UTC, snajima commented on src/uplift/c2c_scraper.py
> +#RECTRAC_PATH = "https://rectrac.pe.cornell.edu/private/webtrac.wsc/history.html?historyoption=inquiry&_csrf_token=9e7d41b4de08bca17c1e7b304c9bae559c02e92712476c3dcb8d0b342f6afeac"
what is this commented line for?

2023-04-16 20:16 UTC, snajima commented on src/uplift/database.py
> +  db_session.merge(teagle_up)
let's condense this to 
```
for gym in [helen_newman, noyes, ... teagle_up]:
   db_session.merge(gym)
```

2023-04-16 20:16 UTC, snajima commented on src/uplift/database.py
> +  db_session.merge(teagle_up)
you can also define the list in multiple lines to avoid clutter, i.e.
```
gyms = [
   helen_newman,
   noyes,
   ...
]

for gym in gyms:
   db_session.merge(gym)
```

2023-04-16 20:16 UTC, snajima commented on src/uplift/models/gym.py
> +            #"times": self.times,
no comment :c

2023-04-16 20:16 UTC, snajima commented on src/uplift/schema.py
> +      query = query.order_by(desc(CapacityModel.updated))
```
query = Capacity.get_query(info=info) \
   .filter(CapacityModel.gym_id == self.id) \
   .order_by(desc(CapacityModel.updated))
```

2023-04-16 20:16 UTC, snajima commented on src/uplift/scrapers/c2c_scraper.sh
> +# cron job */15 06-23 * * * c2c_scraper.sh
same thing

2023-04-16 23:19 UTC, markim21 commented on src/uplift/c2c_scraper.py
> +#RECTRAC_PATH = "https://rectrac.pe.cornell.edu/private/webtrac.wsc/history.html?historyoption=inquiry&_csrf_token=9e7d41b4de08bca17c1e7b304c9bae559c02e92712476c3dcb8d0b342f6afeac"
This is the online student portal with gym membership/visits information. The url is there because I wanted to try scraping information from it. ...didn't work though, so I commented it out (so I wouldn't accidentally use it). I can uncomment it!

2023-04-16 23:23 UTC, markim21 commented on src/uplift/scrapers/c2c_scraper.sh
> +# cron job */15 06-23 * * * c2c_scraper.sh
Oh this is a comment because I was struggling to make a crontab file for `cron job */15 06-23 * * * c2c_scraper.sh` , but this commented out code should be in its own file. totally forgot I was blocked on this, I might need your assistance to set this up :,)

2023-04-17 19:08 UTC, snajima approved these changes
lgtm! deleting all of the `app` and `app2` folders seem like a pretty big change so do you mind writing a short description in the PR why that was done? (just for documentation purposes) you can merge after!

2023-04-17 19:08 UTC, snajima commented on src/uplift/scrapers/c2c_scraper.sh
> +# cron job */15 06-23 * * * c2c_scraper.sh
yes yes lmk if u need help !

2023-04-19 19:49 UTC, merged